#!/bin/bash
#PBS -l nodes=1:ppn=32  		# Requests 1 node and 8 processors per node
##PBS -l nodes=node02:ppn=32  		# Requests 1 node and 8 processors per node
#PBS -l walltime=72:00:00 	# Sets max walltime for the job to 48 hours
#PBS -j oe			# Merge output and error files as standard output.
##PBS -M zhaoshuai@imech.ac.cn
#PBS -m ae			# Sends email on job abort, begin, and end
#PBS -p 1000

ulimit -s unlimited

date
pwd
[[ ! -f "KPOINTS" ]] && echo -e "102\n2\n0.03\n"|vaspkit|grep "K-Mesh Size"

echo "" > vasp.log
mpirun -np 32 vasp >> vasp.log

TailOut=$(tail -n 1 OUTCAR | awk '{print $1}')
if [ "$TailOut" = "Voluntary" ];then
	touch finished
else
	touch terminated
fi


date
mv /home/szhao/vasp/VASP_TENSION/data/POSCAR /home/szhao/vasp/VASP_TENSION/data/POSCAR.init
cp CONTCAR mv /home/szhao/vasp/VASP_TENSION/data/POSCAR
